name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.githum/workflows/**.yml'
      - 'Makefile'
  # pull_request:
  #   branches: [ "main" ]
jobs:
  build:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: dealday/gcc-arm:latest
    steps:
      - name: compiling code
        run: |
          echo "Compiling code"
      - name: Change to project folder
        uses: actions/checkout@v4
      - name: generating binary with makefile
        run: |
          cd myProject
          make clean
          make all
          echo "Compile done"
  test:
    runs-on: ubuntu-latest
    container:
      image: dealday/gcc-arm:latest
    steps:
      - name: cd to working directory
        uses: actions/checkout@v4
      - name: running test
        run: |
          cd myProject
          make clean_test
          make test
          echo "test done"
  deployToTarget:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: dealday/gcc-arm:latest
    steps:
      - name: cd to working directory
        uses: actions/checkout@v4
      - name: deploying to target
        run: |
          cd myProject
          make deployToTarget
          echo "Succesfully deployed to Target"
